name: test_osm_map
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
    
  # flutter
  flutter_redux: ^0.10.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  osm_flutter_hooks: ^1.0.0
  flutter_osm_plugin: ^0.42.0
  flutter_map: ^0.13.1

  flutter_osrm:
    git:
      url: https://github.com/JaffaKetchup/flutter_osrm.git

  # dart
  redux: ^5.0.0
  built_value: ^8.4.1
  built_collection: ^5.1.1
  freezed_annotation: ^2.2.0
  redux_epics: ^0.15.1
  xml: ^6.2.2
  gpx: ^2.2.1
  map_launcher: ^2.4.0
  location: ^4.4.0
  geocoding: ^2.0.5
  flutter_compass: ^0.7.0
  flutter_nhan_compass: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  built_value_generator: ^8.4.1
  freezed: any
  analyzer: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/coordinates.gpx